[package]
name = "axmon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "axmon"
path = "src/main.rs"

[dependencies]
anyhow = { version = "1" }
async-trait = { version = "0.1" }
axum = { version = "0.7", features = ["ws"] }
bollard = { version = "0.16" }
futures-util = "0.3"
nvml-wrapper = { version = "0.10" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sysinfo = { version = "0.30",features=["linux-netdevs"] }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = "thin"
codegen-units = 1
