/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CpuRouteImport } from './routes/cpu'
import { Route as DiskRouteImport } from './routes/disk'
import { Route as DockerRouteImport } from './routes/docker'
import { Route as GpuRouteImport } from './routes/gpu'
import { Route as MemRouteImport } from './routes/mem'
import { Route as ProcessRouteImport } from './routes/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CpuRoute = CpuRouteImport.update({
  id: '/cpu',
  path: '/cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const DiskRoute = DiskRouteImport.update({
  id: '/disk',
  path: '/disk',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerRoute = DockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => rootRouteImport,
} as any)
const GpuRoute = GpuRouteImport.update({
  id: '/gpu',
  path: '/gpu',
  getParentRoute: () => rootRouteImport,
} as any)
const MemRoute = MemRouteImport.update({
  id: '/mem',
  path: '/mem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cpu': typeof CpuRoute
  '/disk': typeof DiskRoute
  '/docker': typeof DockerRoute
  '/gpu': typeof GpuRoute
  '/mem': typeof MemRoute
  '/process': typeof ProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cpu': typeof CpuRoute
  '/disk': typeof DiskRoute
  '/docker': typeof DockerRoute
  '/gpu': typeof GpuRoute
  '/mem': typeof MemRoute
  '/process': typeof ProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cpu': typeof CpuRoute
  '/disk': typeof DiskRoute
  '/docker': typeof DockerRoute
  '/gpu': typeof GpuRoute
  '/mem': typeof MemRoute
  '/process': typeof ProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cpu' | '/disk' | '/docker' | '/gpu' | '/mem' | '/process'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cpu' | '/disk' | '/docker' | '/gpu' | '/mem' | '/process'
  id:
    | '__root__'
    | '/'
    | '/cpu'
    | '/disk'
    | '/docker'
    | '/gpu'
    | '/mem'
    | '/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CpuRoute: typeof CpuRoute
  DiskRoute: typeof DiskRoute
  DockerRoute: typeof DockerRoute
  GpuRoute: typeof GpuRoute
  MemRoute: typeof MemRoute
  ProcessRoute: typeof ProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpu': {
      id: '/cpu'
      path: '/cpu'
      fullPath: '/cpu'
      preLoaderRoute: typeof CpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disk': {
      id: '/disk'
      path: '/disk'
      fullPath: '/disk'
      preLoaderRoute: typeof DiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker': {
      id: '/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof DockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpu': {
      id: '/gpu'
      path: '/gpu'
      fullPath: '/gpu'
      preLoaderRoute: typeof GpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mem': {
      id: '/mem'
      path: '/mem'
      fullPath: '/mem'
      preLoaderRoute: typeof MemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CpuRoute: CpuRoute,
  DiskRoute: DiskRoute,
  DockerRoute: DockerRoute,
  GpuRoute: GpuRoute,
  MemRoute: MemRoute,
  ProcessRoute: ProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
